// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz6rhpR_kaTMKD1XwBHc__PurGPn_o1X4',
    appId: '1:71049643952:web:5b6fce5a0a4bf1b7e67875',
    messagingSenderId: '71049643952',
    projectId: 'teacher-chatbot-429509',
    authDomain: 'teacher-chatbot-429509.firebaseapp.com',
    storageBucket: 'teacher-chatbot-429509.appspot.com',
    measurementId: 'G-VRPZ75X40V',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqq6jTprlDu5rzp2LQT1HEYMeGTY0UEbw',
    appId: '1:71049643952:ios:11ba100bd97c9049e67875',
    messagingSenderId: '71049643952',
    projectId: 'teacher-chatbot-429509',
    storageBucket: 'teacher-chatbot-429509.appspot.com',
    iosBundleId: 'com.example.aiTeacherChatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz6rhpR_kaTMKD1XwBHc__PurGPn_o1X4',
    appId: '1:71049643952:web:5ca36fa0f5018273e67875',
    messagingSenderId: '71049643952',
    projectId: 'teacher-chatbot-429509',
    authDomain: 'teacher-chatbot-429509.firebaseapp.com',
    storageBucket: 'teacher-chatbot-429509.appspot.com',
    measurementId: 'G-7YFMPJJRVZ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqq6jTprlDu5rzp2LQT1HEYMeGTY0UEbw',
    appId: '1:71049643952:ios:11ba100bd97c9049e67875',
    messagingSenderId: '71049643952',
    projectId: 'teacher-chatbot-429509',
    storageBucket: 'teacher-chatbot-429509.appspot.com',
    iosBundleId: 'com.example.aiTeacherChatbot',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAo4NzVGI9Wy9_r6yVtdKUN4QcPkWFBJM',
    appId: '1:71049643952:android:f6e02e3c7f76ed7de67875',
    messagingSenderId: '71049643952',
    projectId: 'teacher-chatbot-429509',
    storageBucket: 'teacher-chatbot-429509.appspot.com',
  );

}